// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {engine} from '../models';
import {config} from '../models';
import {main} from '../models';

export function BroadcastSystemLog(arg1:string):Promise<void>;

export function CleanupDB():Promise<number>;

export function DeleteFiles(arg1:Array<string>):Promise<void>;

export function DeleteIgnoredGroup(arg1:number):Promise<void>;

export function ExcludeGroup(arg1:string,arg2:Array<string>):Promise<void>;

export function ExportDB():Promise<void>;

export function GetIgnoredGroups():Promise<Array<db.IgnoredGroup>>;

export function GetResults(arg1:number,arg2:number):Promise<engine.ResultsResponse>;

export function GetSettings():Promise<config.Settings>;

export function GetSuspiciousFiles():Promise<Array<main.SuspiciousFile>>;

export function GetThumbnails(arg1:string,arg2:number,arg3:number):Promise<Array<string>>;

export function ImportDB():Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function PurgeBlacklist():Promise<void>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function ResetDB():Promise<void>;

export function ResetSettings():Promise<void>;

export function SaveLogToFile(arg1:string):Promise<void>;

export function SaveSettings(arg1:config.Settings):Promise<void>;

export function StartScan(arg1:Array<string>):Promise<void>;

export function StopScan():Promise<void>;
