// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BroadcastSystemLog(arg1) {
  return window['go']['main']['App']['BroadcastSystemLog'](arg1);
}

export function CheckDependencies() {
  return window['go']['main']['App']['CheckDependencies']();
}

export function CleanupDB() {
  return window['go']['main']['App']['CleanupDB']();
}

export function DeleteFiles(arg1) {
  return window['go']['main']['App']['DeleteFiles'](arg1);
}

export function DeleteIgnoredGroup(arg1) {
  return window['go']['main']['App']['DeleteIgnoredGroup'](arg1);
}

export function DownloadDependencies() {
  return window['go']['main']['App']['DownloadDependencies']();
}

export function ExcludeGroup(arg1, arg2) {
  return window['go']['main']['App']['ExcludeGroup'](arg1, arg2);
}

export function ExportDB() {
  return window['go']['main']['App']['ExportDB']();
}

export function GetDebugInfo() {
  return window['go']['main']['App']['GetDebugInfo']();
}

export function GetDuplicateStats() {
  return window['go']['main']['App']['GetDuplicateStats']();
}

export function GetIgnoredGroups() {
  return window['go']['main']['App']['GetIgnoredGroups']();
}

export function GetResults(arg1, arg2) {
  return window['go']['main']['App']['GetResults'](arg1, arg2);
}

export function GetScanStatus() {
  return window['go']['main']['App']['GetScanStatus']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetSuspiciousFiles() {
  return window['go']['main']['App']['GetSuspiciousFiles']();
}

export function GetThumbnails(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetThumbnails'](arg1, arg2, arg3);
}

export function ImportDB() {
  return window['go']['main']['App']['ImportDB']();
}

export function ListDirs(arg1) {
  return window['go']['main']['App']['ListDirs'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function PurgeBlacklist() {
  return window['go']['main']['App']['PurgeBlacklist']();
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function ResetDB() {
  return window['go']['main']['App']['ResetDB']();
}

export function ResetSettings() {
  return window['go']['main']['App']['ResetSettings']();
}

export function SaveLogToFile(arg1) {
  return window['go']['main']['App']['SaveLogToFile'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartScan(arg1) {
  return window['go']['main']['App']['StartScan'](arg1);
}

export function StopScan() {
  return window['go']['main']['App']['StopScan']();
}
